Tomohiro/fluentular

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5960699574994158787">Bundle Update as a Service - Tachikoma.io</a>
=> Exec tachikoma update 20150113093216

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5963236322947122179">Bundle Update as a Service - Tachikoma.io</a>
=> Exec tachikoma update 20150120093225

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5965773089749800945">Bundle Update as a Service - Tachikoma.io</a>
=> Exec tachikoma update 20150127093238

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5968309845361335396">Bundle Update as a Service - Tachikoma.io</a>
=> Exec tachikoma update 20150203093245

README.md, app.rb
=> Simplify "Example" style

README.md, app.rb
=> Display running fluentd version

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5978456864137577065">Bundle Update as a Service - Tachikoma.io</a>
=> Exec tachikoma update 20150303093324

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5993676415157757810">Bundle Update as a Service - Tachikoma.io</a>
=> Exec tachikoma update 20150414093028

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5996213130990773509">Bundle Update as a Service - Tachikoma.io</a>
=> Exec tachikoma update 20150421093027

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build5998749849403204526">Bundle Update as a Service - Tachikoma.io</a>
=> Exec tachikoma update 20150428093031

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6003823276297904309">Bundle Update as a Service - Tachikoma.io</a>
=> Exec tachikoma update 20150512093033

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6006359991241921259">Bundle Update as a Service - Tachikoma.io</a>
=> Exec tachikoma update 20150519093033

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6008896713380285197">Bundle Update as a Service - Tachikoma.io</a>
=> Exec tachikoma update 20150526093033

Gemfile.lock, app.rb
Including [patch](https://github.com/Tomohiro/fluentular/pull/63#issuecomment-108208607) original created by @repeatedly, thanks :star2:
=> Supporrt Fluentd v0.12.11

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6033502666270040483">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6033502666270040483">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20150802070607

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6036039388294980879">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6036039388294980879">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20150809070606

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6038576095863812003">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6038576095863812003">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20150816070616

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6041112816821464957">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6041112816821464957">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20150823070615

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6046186222336157441">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6046186222336157441">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20150906070621

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6051259632540165585">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6051259632540165585">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20150920070625

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6056333106462898606">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6056333106462898606">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20151004070637

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6066479960471313545">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6066479960471313545">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20151101070555

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6069016676815294038">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6069016676815294038">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20151108070550

app.rb
GitHub Courners: http://tholman.com/github-corners/
=> Use GitHub Courners instead of GitHub ribbons

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6074090106270600586">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6074090106270600586">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20151122070558

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6079163539610700409">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6079163539610700409">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20151206070604

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6081700253468368373">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6081700253468368373">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20151213070556

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6086773690287580978">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6086773690287580978">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20151227070621

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6091847112103004586">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6091847112103004586">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160110070608

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6094383831605813381">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6094383831605813381">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160117070621

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6101993981334068492">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6101993981334068492">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160207070637

LICENSE, README.md, app.rb
https://fluentular.herokuapp.com
=> Support SSL url
